config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'days#index'

  resources :days do
    resources :foods
  end

  get '/days/:day_id/nutrients/:id' => 'nutrients#show'

  get '/update_measures' => 'foods#update_measures'
  get '/update_nutrients' => 'foods#update_nutrients'

  get '/about' => 'static_pages#about'

  resources :users

end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :user
  has_many :foods
end

app/controllers/days_controller.rb
class DaysController < ApplicationController

  include ApplicationHelper

  def index
    @day = Day.last
    redirect_to day_path(@day)
  end

  def create
    redirect_to day_path(@day)
  end

  def show
    if get_current_user.days.where(id: params[:id]).count > 0
      @day = Day.find(params[:id])
      @foods = @day.foods
    else
      redirect_to days_path
    end
  end
end

app/views/days/_diet_goals.html.haml
- titletext="Guidelines for Healthful Eating"

%div{class: 'row'}
  %div{class: 'col-xs-6'}
    %table{:class => "table table-condensed", title: titletext}
      =titletext
      %thead
        %tr
          %th  Goal
          %th  Met

      %tbody
        = render :partial => "diet_goals_table_body"

app/views/days/_diet_goals_table_body.html.haml
%tr
  %td= "Cholesterol: less than 300 mg"
  %td= goal_cholesterol(@foods)
%tr
  %td= "Dietary Fat: < 30% of calories"
  %td= goal_dietaryfat(@foods)
%tr
  %td= "Saturated Fat: < 10% of calories"
  %td= goal_satfat(@foods)

%tr
  %td= "Trans Fat: 0% of calories"
  %td= goal_transfat(@foods)
%tr
  %td= "Dietary Fiber: >= 15g"
  %td= goal_fiber(@foods)
%tr
  %td= "Dietary Sodium: less than 2300mg"
  %td= goal_sodium(@foods)

%tr
  %td= "At least 400 g (5 portions) of fruits and vegetables a day (2). Potatoes, sweet potatoes, cassava and other starchy roots are not classified as fruits or vegetables."
  %td= goal_fruit_and_veg(@foods)

app/views/days/_energy_density_tab.html.haml
= content_tag :canvas, "", id: "energy-barchart", data: { energydensity: energy_density_data }
    

app/views/days/_summary_tab_content.html.haml
%div{class: 'row'}
  %div{class: 'col-sm-6'}
    %table{:class => "table table-condensed", title: "Nutrient Totals" }
      Nutrient Totals
      %thead
        %tr
          %th  Food
          %th  Amount
      %tbody
        %tr
          %td= "Calories"
          %td= daily_helper(Nutrients::ENERC_KCAL, @foods )
        %tr
          %td= "Protein"
          %td= daily_helper(Nutrients::PROCNT, @foods )
        %tr
          %td= "Carbs"
          %td= daily_helper(Nutrients::CHOCDF, @foods )
        %tr
          %td= "Fat"
          %td= daily_helper(Nutrients::FAT, @foods )
        %tr
          %td= "Fiber"
          %td= daily_helper(Nutrients::FIBTG, @foods )

  %div{class: 'col-sm-6'}
    = content_tag :canvas, "", id: "macros-piechart", data: { piechart: piechartdata }

app/views/days/_tab_pane.html.haml
%table{:class => "table table-condensed" }
  %thead
    %tr
      %th  Nutrient
      %th  Amount
      %th  Unit
  %tbody
    - tab_pane_nutrients(category).each do |v|
      %tr
        %td=v[0]
        %td=daily_helper(v[0], @foods)
        %td=v[1]

app/views/days/show.html.haml
- if not previous_day_link.blank?
  =link_to "Previous Day", '#'
- else
  =link_to("Previous Day", '#')


- if next_day_link.blank?
  %p Next day
- else
  =link_to "Next Day", '#'

%h4= display_the_date_helper


= link_to "Add Serving" , new_day_food_path(@day)


%table{:class => "table table-condensed" }
  %thead
    %tr
      %th  Food
      %th  Amount
      %th  Measure
      %th  Calories
  %tbody
    - @foods.each do |f|
      %tr
        %td
          %li= link_to f.name, edit_day_food_path(@day, f), title: "Edit entry for #{f.name}"

        %td= "#{f.amount}"
        %td= "#{f.measure}"
        %td= "#{formatit(f.calories)}"

%ul.nav.nav-tabs
  %li.active
    %a{"data-target" => "#summary", "data-toggle" => "tab", href: "#"} Summary
  %li
    %a{"data-target" => "#vitamins", "data-toggle" => "tab", href: "#"} Vitamins
  %li
    %a{"data-target" => "#minerals", "data-toggle" => "tab", href: "#"} Minerals
  %li
    %a{"data-target" => "#lipids", "data-toggle" => "tab", href: "#"} Lipids
  %li
    %a{"data-target" => "#amino_acids", "data-toggle" => "tab", href: "#"} Amino Acids
  %li
    %a{"data-target" => "#energy_density", "data-toggle" => "tab", href: "#"} Energy Density
  %li
    %a{"data-target" => "#diet_goals", "data-toggle" => "tab", href: "#"} Healthy Diet Goals

.tab-content
  #summary.tab-pane.fade.in.active
    =render :partial => "summary_tab_content"
  #vitamins.tab-pane.fade
    =render :partial => "tab_pane", locals: { category: "Vitamins" }
  #minerals.tab-pane.fade
    =render :partial => "tab_pane", locals: { category: "Minerals" }
  #lipids.tab-pane.fade
    =render :partial => "tab_pane", locals: { category: "Lipids" }
  #amino_acids.tab-pane.fade
    =render :partial => "tab_pane", locals: { category: "Amino Acids" }
  #diet_goals.tab-pane.fade
    =render :partial => "diet_goals"
  #energy_density.tab-pane.fade
    =render :partial => "energy_density_tab"