config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'days#index'

  resources :days do
    resources :foods
  end

  get '/days/:day_id/nutrients/:id' => 'nutrients#show'

  get '/update_measures' => 'foods#update_measures'
  get '/update_nutrients' => 'foods#update_nutrients'

  get '/about' => 'static_pages#about'

  resources :users

end

app/models/food.rb
class Food < ApplicationRecord

  belongs_to :day

  include Utility
  include ApplicationHelper

  def calories
    nutrient(ENERC_KCAL)
  end

  def nutrients_by_category(x)
    results = nil
    response = Fdcapi.caching_find(fdcid)
    if not response.nil?
      nutrients = response['foodNutrients']
      results = nutrients.select {|hash|hash['group'] == x }
    end
  end

  def carb_energy
    macro_energy('cf', CALORIES_PER_GRAM_CARB, CHOCDF)
  end

  def fat_energy
    macro_energy('ff', CALORIES_PER_GRAM_FAT, FAT)
  end

  def protein_energy
    macro_energy('pf', CALORIES_PER_GRAM_PROTEIN, PROCNT)
  end

  def macro_energy(tag, standard_conversion_factor, nutrient)
    factor = calories_per_gram(fdcid, tag, standard_conversion_factor)
    grams = nutrient_per_serving(nutrient,  fdcid, measure, amount)
    factor * grams
  end

  def nutrient(nutrient_name)
    nutrient_per_serving(nutrient_name, fdcid, measure, amount )
  end

  def name
    name = nil
    response = Fdcapi.caching_find(fdcid)
    if not response.body.nil? || response.body.empty?
      name = response['description']
    end
    name
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  include ApplicationHelper

  def new
    @food = Food.new
    if params[:search]
      @items = caching_search(params[:search])
      @items = list_for_select_options(@items)
    end
    @day = current_user.days.where(id: params[:day_id]).first
  end

  def show
    @food = Food.find(params[:id])
  end

  def create
    day_id = params[:day_id]
    @day = Day.find(day_id)
    @food = @day.foods.build(food_params)

    if @food.save
      redirect_to day_path(@day)
    else
      render :new
    end
  end

  def edit
    food_id = params[:id]
    @food = Food.find(food_id)
    day_id = params[:day_id]
    @day = Day.find(day_id)
  end

  def update
    @day = Day.find(params[:day_id])
    @food = Food.find(params[:id])

    if @food.update_attributes(food_params)
      redirect_to day_path(@day)
    else
      render :edit
    end
  end

  def update_measures
    if params[:id]
      @measures = measures_for_food(params[:fdcid])

      current_food = Food.find(params[:id])
      @nutrients = nutrients_for_food_panel(current_food.fdcid,
                                            current_food.amount,
                                            current_food.measure,
                                           )
      respond_to do |format|
        format.json { render json: { measures: @measures, nutrients: @nutrients,
                                     selected_measure: current_food.measure }}
      end
    else # called upon change in food selection
      fdcid = params[:fdcid]
      @measures = measures_for_food(fdcid)
      amount = 1.0
      @nutrients = nutrients_for_food_panel(fdcid, amount)
      respond_to do |format|
        format.json { render json: { measures: @measures, nutrients: @nutrients }}
      end
    end
  end

  def destroy
    @day = Day.find(params[:day_id])
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to day_path(@day)
  end

  def update_nutrients
    
    fdcid = params[:fdcid]
    measure = params[:measure]
    amount = 1.0

    if params[:amount]
      amount = params[:amount]
    end

    @nutrients = nutrients_for_food_panel(fdcid, amount, measure)
    respond_to do |format|
      format.json { render json: { nutrients: @nutrients }}
    end
  end

  private

  def food_params
    params.require(:food).permit(:fdcid, :amount, :measure).merge(user_id: current_user.id)
  end
end

app/helpers/foods_helper.rb
# coding: utf-8
module FoodsHelper

  include Nutrients

  def tab_pane_nutrients(category)
    y = case category
        when 'Vitamins'
          [
            [VITA_IU, 'IU'],
            [FOL, 'µg'],
            [THIA, 'mg'],
            [RIBF, 'mg'],
            [NIA, 'mg'],
            [PANTAC, 'mg'],
            [VITB6A, 'mg'],
            [VITB12, 'µg'],
            [VITC, 'mg'],
            [VITD, 'µg'],
            [TOCPHA, 'mg'],
            [VITK1,  'µg']
          ]
        when 'Minerals'
          [
            [CA, 'mg'],
            [CU, 'mg'],
            [FE, 'mg'],
            [MG, 'mg'],
            [MN, 'mg'],
            [P, 'mg'],
            [K, 'mg'],
            [SE, 'µg'],
            [NA, 'mg'],
            [ZN, 'mg']
          ]
        when 'Lipids'
          [
            [FASAT, 'g'],
            [FAMS, 'g'],
            [FAPU, 'g'],
            [CHOLE, 'mg'],
            [FATRN, 'mg'],
            ['Omega 3', 'g'],
            ['Omega 6', 'g'],
            [F18D3CN3, 'g'],
            [F20D3N3, 'mg'],
            [F22D6, 'mg'],
            [F20D5, 'mg'],
            [F22D5, 'mg']
          ]

        when 'Amino Acids'
          [
            [ALA_G, 'g'],
            [ARG_G, 'g'],
            [ASP_G, 'g'],
            [CYS_G, 'g'],
            [GLU_G, 'g'],
            [GLY_G, 'g'],
            [HISTN_G, 'g'],
            [HYP, 'g'],
            [ILE_G, 'g'],
            [LEU_G, 'g'],
            [LYS_G, 'g'],
            [MET_G, 'g'],
            [PHE_G, 'g'],
            [PRO_G, 'g'],
            [SER_G, 'g'],
            [THR_G, 'g'],
            [TRP_G, 'g'],
            [TYR_G, 'g'],
            [VAL_G, 'g']
          ]
        end
    y
  end

end

app/views/foods/_delete_entry.html.haml
= button_to "Remove entry", { action: "destroy" }, class: "btn btn-danger", :method => :delete, id: "my_id"

app/views/foods/_food_form.html.haml
= form_for ([@day, @food]),  {:html => {:class => "form-inline"}}  do |f|
  %div{:class => 'form-group'}
    = f.label :amount
    = f.text_field :amount, class: "form-control"
  %div{:class => 'form-group'}
    = f.label :measure
    = f.select :measure, "", {}, {class: "form-control"}
  %div{:class => 'form-group'}
    = f.hidden_field :fdcid
  %div{:class => 'form-group'}
    = f.submit  "Save", class: "form-control btn-primary"

app/views/foods/_nested_grid.html.haml
%div{:class =>'row'}
  %div{:class =>'col-sm-4'}
    = render :partial => "text_field_tag", locals: { nutrient: "Energy", unit: "calories" }
  %div{:class =>'col-sm-4'}
    = render :partial => "text_field_tag", locals: { nutrient: "Water" , unit: 'g'}
  %div{:class =>'col-sm-4'}
    = render :partial => "text_field_tag", locals: { nutrient: "Fiber" , unit: 'g'}
%div{:class =>'row'}
  %div{:class =>'col-sm-4'}
    = render :partial => "text_field_tag", locals: { nutrient: "Protein", unit: 'g' }
  %div{:class =>'col-sm-4'}
    = render :partial => "text_field_tag", locals: { nutrient: "Carbs", special_nutrient_name: "Carbohydrate", unit: 'g' }
  %div{:class =>'col-sm-4'}
    = render :partial => "text_field_tag", locals: { nutrient: "Fat" , unit: 'g'}

app/views/foods/_new_form.html.haml
= form_tag new_day_food_path, :class => "form-inline", :method => :get do
  %div{:class => 'form-group'}
    = label_tag "search", "Search: "
    = text_field_tag "search", params[:search], class: "form-control", placeholder: "e.g. Strawberries"
    = submit_tag "Submit", class: "form-control"

app/views/foods/_search_results.html.haml
-# row 2
%div{:class =>'row'}
  %div{:class =>'col-sm-12'}
    - if not @items.nil?
      = select_tag(:food_type_id, options_for_select(@items), size: 20,
      :class => "form-control" )

-# row 3 text panel 2 rows of 3 columns
%div{:class =>'row'}
  %div{:class =>'col-sm-12'}
    = render :partial => 'nested_grid'


-# row 4 quantity select; measure drown-down, and add button
%div{:class =>'row foodformrow'}
  %div{:class =>'col-sm-12'}
    = render :partial => 'food_form'

app/views/foods/_table.html.haml
%table{:class => "table table-condensed" }
  %tbody
    %th=category
    - @food.nutrients_by_category(category).each do |n|
      %tr
        %td= "#{n['name']} "
        %td= "#{n['value']} #{n['unit']}"

app/views/foods/_tables.html.haml
%div{:class => "col-xs-3"}
  = render :partial => "table", locals: { category: "Proximates" }
%div{:class => "col-xs-3"}
  = render :partial => "table", locals: { category: "Vitamins" }
%div{:class => "col-xs-3"}
  = render :partial => "table", locals: { category: "Minerals" }
%div{:class => "col-xs-3"}
  = render :partial => "table", locals: { category: "Lipids" }

app/views/foods/_text_field_tag.html.haml
%p
  %span{:class => 'nutrient-label'}
    - if defined? special_nutrient_name
      #{special_nutrient_name}:
    - else
      #{nutrient}:
  %span{id: nutrient }
  %span=unit

app/views/foods/edit.html.haml
%h4=@food.name
-# row 1
%div{:class =>'row'}
  %div{:class =>'col-sm-12'}
    = render :partial => 'nested_grid'

-# row 4 quantity select; measure drown-down, and add button
%div{:class =>'row foodformrow'}
  %div{:class =>'col-sm-12'}
    = render :partial => 'food_form'

%div{:class =>'row foodformrow'}
  %div{:class =>'col-sm-12'}
    = render :partial => 'delete_entry'

app/views/foods/index.html.haml
=link_to "Previous Day", previous_day_link


- if next_day_link.empty?
  %p Next day
- else
  =link_to "Next Day", next_day_link


%h4= display_the_date_helper

- if today?
  = link_to "Add Serving" , new_food_path


%table{:class => "table table-condensed" }
  %thead
    %tr
      %th  Food
      %th  Amount
      %th  Measure
      %th  Calories
  %tbody
    - @foods.each do |f|
      %tr
        %td
          - if next_day_link.empty?
            %li= link_to f.name, edit_food_path(f, f), title: "Edit entry for #{f.name}"
          - else
            %li= link_to f.name, food_path(f, f), title: "View entry for #{f.name}"
        %td= "#{f.amount}"
        %td= "#{f.measure}"
        %td= "#{formatit(f.calories)}"

%ul.nav.nav-tabs
  %li.active
    %a{"data-target" => "#summary", "data-toggle" => "tab", href: "#"} Summary
  %li
    %a{"data-target" => "#vitamins", "data-toggle" => "tab", href: "#"} Vitamins
  %li
    %a{"data-target" => "#minerals", "data-toggle" => "tab", href: "#"} Minerals
  %li
    %a{"data-target" => "#lipids", "data-toggle" => "tab", href: "#"} Lipids
  %li
    %a{"data-target" => "#amino_acids", "data-toggle" => "tab", href: "#"} Amino Acids
  %li
    %a{"data-target" => "#energy_density", "data-toggle" => "tab", href: "#"} Energy Density
  %li
    %a{"data-target" => "#diet_goals", "data-toggle" => "tab", href: "#"} Healthy Diet Goals

.tab-content
  #summary.tab-pane.fade.in.active
    =render :partial => "summary_tab_content"
  #vitamins.tab-pane.fade
    =render :partial => "tab_pane", locals: { category: "Vitamins" }
  #minerals.tab-pane.fade
    =render :partial => "tab_pane", locals: { category: "Minerals" }
  #lipids.tab-pane.fade
    =render :partial => "tab_pane", locals: { category: "Lipids" }
  #amino_acids.tab-pane.fade
    =render :partial => "tab_pane", locals: { category: "Amino Acids" }
  #diet_goals.tab-pane.fade
    =render :partial => "diet_goals"
  #energy_density.tab-pane.fade
    =render :partial => "energy_density_tab"

app/views/foods/new.html.haml
-# row 1
%div{:class =>'row foodformrow'}
  %div{:class =>'col-sm-12'}
    = render :partial => "new_form"
  - if @items && @items.count > 0
    = render :partial => "search_results"

app/views/foods/show.html.haml
%h4=@food.name
%dl
  %div{:class => "panel panel-default", :style=> 'border-width: 1px; border-color: black;'}
    %div{:class => "panel-heading"}='Nutrition Information'
    %div{:class => "panel-body"}
      = render :partial => "tables"